### ISSUE TITLE
mapa mental de conjuntos y relaciones 

### ISSUE THREAD

**Issue by bibiana-m** [SistemasTecTlaxiaco/actividad-4-mapa-mental-bibiana-m#2]
[mapa mental de conjuntos y relaciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-bibiana-m/files/12690962/mapa.mental.de.conjuntos.y.relaciones.pdf)

**Comment by elisa1223** [comment]
Manejo conceptual y dominio del tema     20%
Relacion entre los conceptos incluidos en el mapa   22%
Calidad de la presentación                  20%
Jerarquía                  22%

Calificación 16.8 / 20
Evaluado por el quipo de Elisa Sánchez  Coronel

**Comment by josealfredo79** [comment]
Revisado...
